function msg = getMsgStr(thisphase)
switch(thisphase)
    case 'natural'
        msg={'Please read the following words in your natural speaking voice. '};			
    case 'pre'
        msg={'Please read the words in your normal speaking voice. '};
    case 'pract1'         % pract1
        msg={'Please read the words displayed on the screen.',...
			'You will hear your speech through the headphones as you read the words.',...
            '',...
			'It will tell you how loud you''ve spoken. Please carefully',...
			'adjust your loudness to enter the acceptance range. ',...
			'',...
			'A trial will be repeated until your loudness is correct.',...
			};
    case 'pract2'		% pract2
        msg={'Well done!',...
			'',...
			'Now, in addition to the loudness, you will be given feedback about ', ...
            'how long you''ve spoken.',...
            '', ...
			'Please carefully adjust your word length to enter the correct range.',...
			'',...
			'A trial will be repeated until both your loudness and your word length.', ...
            'are correct.'};
    case 'start'	% start
        msg={'Good job!',...
			'',...
			'Now, please try to keep the volume and speed you''ve learned ',...
			'throughout the rest of the experiment.'};
    case 'ramp'
        msg={''};
    otherwise,
        msg={''};
end
    
