function msg = getMsgStr(thisphase)
switch(thisphase)
    case 'natural'
        msg={'Please read the following words in your natural speaking voice. '};			
    case 'pre'
        msg={'Please read the following words in your normal speaking voice. ',...
			'',...
			'Similar to the previous task, you will be given feedback about ',...
            'the loudness and duration of your speech. Please try to adjust ',...
            'your voice loudness and speed to match the green areas of the ',...
            'feedback bands. ',...
			};
    case 'pract1'         % pract1
        msg={'Please read the words displayed on the screen. .',...
			'You will hear your speech through the headphones as you read the words',...
            '',...
			'It will tell you how loud you''ve spoken. Please carefully',...
			'adjust your loudness to hit the middle green area. ',...
			'',...
			'A trial will be repeated until you successfully land in this area.',...
			'',...
			'Press "play" to continue.',...
			};
    case 'pract2'		% pract2
        msg={'Well done!',...
			'',...
			'Now, in addition to the volume meter, a speed meter is',...
			'displayed. It will tell you how fast you''ve spoken ',...
			'Please carefully adjust your word length to hit the middle green area',...
			'',...
			'A trial will be repeated until you simultaneously lands in the green ',...
			'areas of both the volume and speed meters. Press "play" to continue.'};
    case 'start'	% start
        msg={'Good job!',...
			'',...
			'Now, the trials will not repeat even if you fall out of the green areas.',...
			'However, please try to keep the volume and speed you''ve learned ',...
			'throughout the rest of the experiment.',...
			'',...
			'Press "play" to continue'};
    case 'ramp'
        msg={''};
    otherwise,
        msg={''};
end
    
