'use strict';(function(d){function c(){this._events={};this._maxListeners=10}function b(a,b,e,c,d){this.type=a;this.listener=b;this.scope=e;this.once=c;this.instance=d}b.prototype.fire=function(a){this.listener.apply(this.scope||this.instance,a);if(this.once)return this.instance.removeListener(this.type,this.listener,this.scope),!1};c.prototype.eachListener=function(a,b){var e=null,c=null,d=null;if(this._events.hasOwnProperty(a)){c=this._events[a];for(e=0;e<c.length;e+=1)if(d=b.call(this,c[e],e),
!1===d)e-=1;else if(!0===d)break}return this};c.prototype.addListener=function(a,f,e,c){this._events.hasOwnProperty(a)||(this._events[a]=[]);this._events[a].push(new b(a,f,e,c,this));this.emit("newListener",a,f,e,c);this._maxListeners&&!this._events[a].warned&&this._events[a].length>this._maxListeners&&("undefined"!==typeof console&&console.warn("Possible EventEmitter memory leak detected. "+this._events[a].length+" listeners added. Use emitter.setMaxListeners() to increase limit."),this._events[a].warned=
!0);return this};c.prototype.on=c.prototype.addListener;c.prototype.once=function(a,b,e){return this.addListener(a,b,e,!0)};c.prototype.removeListener=function(a,b,e){this.eachListener(a,function(c,d){c.listener===b&&(!e||c.scope===e)&&this._events[a].splice(d,1)});this._events[a]&&0===this._events[a].length&&delete this._events[a];return this};c.prototype.off=c.prototype.removeListener;c.prototype.removeAllListeners=function(a){a&&this._events.hasOwnProperty(a)?delete this._events[a]:a||(this._events=
{});return this};c.prototype.listeners=function(a){if(this._events.hasOwnProperty(a)){var b=[];this.eachListener(a,function(a){b.push(a.listener)});return b}return[]};c.prototype.emit=function(a){for(var b=[],c=null,c=1;c<arguments.length;c+=1)b.push(arguments[c]);this.eachListener(a,function(a){return a.fire(b)});return this};c.prototype.setMaxListeners=function(a){this._maxListeners=a;return this};"function"===typeof define&&define.amd?define(function(){return c}):d.EventEmitter=c})(this);
StackExchange.realtime=function(){function d(){if(!(null==m||1!=m.readyState))for(var a=0,b=r.length;a<b;a++)c("sending: "+r[a]),m.send(r[a])}function c(a){StackExchange.options.user.isDeveloper&&console.log(a)}function b(){q.on("hb",function(a){m.send(a)})}function a(a){r.push(a);d()}function f(a,b){1!=$("#vote-accepted-"+a.answerid).length&&($(".vote-accepted-on").remove(),b||$('.vote input[value="'+a.answerid+'"]').parent().append('<span class="vote-accepted-on" title="The question owner accepted this as the best answer">accepted</span>'))}
function e(){$("#new-answer-activity").remove();$("#answers-header").prepend(u)}function g(a){var b=$(".question[data-questionid="+a.id+"], .answer[data-answerid="+a.id+"]"),c=$('<div class="new-post-activity" data-postid="'+a.id+'">an edit has been made to this post; click to load</div>');0<b.find(".new-post-activity[data-postid="+a.id+"]").length||b.prepend(c.click(function(){$(".new-post-activity[data-postid="+a.id+"]").remove();$.get("/posts/"+a.id+"/ajax-load-mini?title=true",w(b.find(".postcell, .answercell"),
a))}))}function i(a,b){return a.index<b.index?-1:a.index>b.index?1:0}function k(){var a=[],b;for(b in j)j.hasOwnProperty(b)&&a.push(j[b]);a=a.sort(i);for(b=0;b<a.length;b++){var c=a[b];$("#question-summary-"+c.id).remove();$(c.body).prependTo("#question-mini-list, #questions").hide().fadeIn()}l(0);null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.applyPrefs(!0,p);"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);h();$(".new-post-activity").remove();j={}}
function l(a){var b=document.title.replace(/^\(\d*\*?\) /,"");0<a&&(b="("+a+") "+b);window.setTimeout(function(){$(document).attr("title",b)},200)}function h(){for(var a=$("span.relativetime"),b=0;b<a.length;b++)if(a[b].title){var c;c=new Date(a[b].title);c=((new Date).getTime()-c.getTime())/1E3;var e=Math.floor(c/86400);if(c=isNaN(e)||0>e||31<=e?void 0:0==e&&(2>c&&"just now"||60>c&&Math.floor(c)+(s?"s ago":" secs ago")||120>c&&(s?"1m ago":"1 min ago")||3600>c&&Math.floor(c/60)+(s?"m ago":" mins ago")||
7200>c&&(s?"1h ago":"1 hour ago")||86400>c&&Math.floor(c/3600)+(s?"h ago":" hours ago")))a[b].innerHTML=c}}var n,m,j={},o=[],v=0,r=[],t=!1,s=!1,p,q=new EventEmitter,u=function(){var a=Object.keys(o).length;return $('<div id="new-answer-activity">'+a+" new answer"+(1<a?"s":"")+" to this question</div>").click(function(){StackExchange.realtime.expandAnswers()})},w=function(a,b){return function(c){var e=$(c).find(".postcell, .answercell");a.replaceWith(e.hide());c=$(c).attr("data-title");null!=c&&$("h1 a.question-hyperlink").text(c);
e.fadeIn(400,function(){StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts();styleCode()});StackExchange.comments.init({post:e});StackExchange.vote.init(b.id);StackExchange.vote||StackExchange.question.bindAnonymousVoteDisclaimers();a.find("a[id^='link-post-']").click(function(a){if(!a.ctrlKey&&!a.metaKey)return StackExchange.question.showShareTip($(this),options.showCitation),!1});StackExchange.question.bindSuggestedEditPopupLinks();StackExchange.question.initShareLinks();
window.history.pushState(b,"new post","#"+b.id)}},x=function(){var a=Object.keys(j).length;l(a);return $('<div class="new-post-activity">'+a+" question"+(1<a?"s":"")+" with new activity</div>").click(function(){StackExchange.realtime.expandActiveQuestions()})};return{init:function(a){n=a;if("WebSocket"in window||"MozWebSocket"in window){if(m)try{c("closing WebSocket"),m.close()}catch(e){}m||(c("opening WebSocket"),m="WebSocket"in window?new WebSocket(n):new MozWebSocket(n),m.onopen=function(){t||
(t=!0);v=0;c("WebSocket opened");d();b();setInterval(h,6E4)},m.onmessage=function(a){a=$.parseJSON(a.data);q.emit(a.action,a.data)},m.onclose=function(){m=null;c("WebSocket closed");5>v&&(v++,c("reconnect attempt:"+v),setTimeout('StackExchange.realtime.init("'+n+'")',5E3*Math.random()))},m.onerror=function(){c("WebSocket failed");m=null})}},expandActiveQuestions:k,expandAnswers:function(){var a=$("#answers #answers-header .answers-subheader h2"),b=parseInt(a.text().match(/^\d*\*?/))+o.length;isNaN(b)&&
(b=o.length);a.text(b+" Answer"+(1<b?"s":""));$("#new-answer-activity").remove();var c=$("#answers #answers-header");$.each(o,function(a,b){$.get("/posts/"+b+"/ajax-load-mini",function(a){a=$(a);a.insertAfter(c).hide().fadeIn(400,function(){StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts();styleCode()});StackExchange.comments.init({post:a});StackExchange.vote.init(b)})});StackExchange.vote||StackExchange.question.bindAnonymousVoteDisclaimers();c.find("a[id^='link-post-']").click(function(a){if(!a.ctrlKey&&
!a.metaKey)return StackExchange.question.showShareTip($(this),options.showCitation),!1});StackExchange.question.bindSuggestedEditPopupLinks();StackExchange.question.initShareLinks();h();o=[]},subscribeToActiveQuestions:function(b,c,e,f,d,g,h){b=b+"-"+c;p=e;s=g;a(b);q.on(b,function(a){a=$.parseJSON(a);if(null!=d)for(var b=0;b<d.length;b++)if(-1==$.inArray(d[b],a.tags))return;null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.isIgnored(a.body)||(j[a.id]={id:a.id,body:a.body,index:(new Date).getTime(),
siteid:a.siteid},$(".new-post-activity").remove(),$("#question-mini-list, #questions").prepend(x),f&&k());null!=h&&h(a)})},subscribeToInboxNotifications:function(){if(null!=StackExchange.options.user.accountId){var b=StackExchange.options.user.accountId+"-inbox";a(b);q.on(b,function(a){$(".unreadCount").remove();var b=$('<a class="unreadCount" title="unread messages in your inbox">'+a+"</a>").insertAfter(".genu");$("#portalLink .unreadCount").css({marginTop:b.css("margin-top"),opacity:1},2E3);genuwine.setUnreadCount(a)})}},
subscribeToQuestion:function(b,c){var d=b+"-question-"+c;a(d);q.on(d,function(a){a=$.parseJSON(a);if(a.acctid!=StackExchange.options.user.accountId)switch(a.a){case "score":var b=$('.vote input[value="'+a.id+'"]').siblings(".vote-count-post");b.text()!=a.score&&(b.text(a.score),0==$(":animated").length&&b.fadeTo("fast",0.7).fadeTo("fast",1),StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts());break;case "comment-add":0==$("#comment-"+a.commentid).length&&(a=$("#comments-link-"+
a.id),b=a.data("comments-count")||0,b++,a.data("comments-count",b),a.attr("title","expand to show all comments on this post, or add one of your own"),a.html("add / show <b>"+b+"</b> more comment"+(1<b?"s":"")).show().fadeTo("fast",0.7).fadeTo("fast",1));break;case "answer-add":0==$("#answer-"+a.answerid).length&&(o.push(a.answerid),StackExchange.cardiologist.isHeartBeating()?StackExchange.helpers.DelayedReaction(e,5E3).trigger():e(),StackExchange.cardiologist.notifiedOfNewAnswer());break;case "accept":f(a);
break;case "unaccept":f(a,!0);break;case "post-edit":g(a)}})},subscribeToReputationNotifications:function(b){null!=StackExchange.options.user.accountId&&(b=b+"-"+StackExchange.options.user.userId+"-reputation",a(b),q.on(b,function(a){var b=$("#hlinks .reputation-score");b.text()!=a.score&&(0==$(":animated").length&&b.fadeTo("fast",0.8).fadeTo("fast",1),b.text(a))}))},subscribeToSuggestedEdits:function(b){b+="-suggested-edits-count";a(b);q.on(b,function(a){var b=$(".suggested-edits-count");b.text()!=
a&&(0==$(":animated").length&&b.fadeTo("fast",0.5).fadeTo("fast",1),b.text(a))})},updateRelativeDates:h}}();"use strict";StackExchange.anonymous={};
var gauth=function(){return{informStackAuth:function(d){if(gauth.enabled()){var c=document.domain;"meta."==c.substr(0,5)&&(c=c.substr(4,c.length-4));var b=$.cookie("gauth");if(null==b)$.cookie("gauth",null,{path:"/",domain:c}),$.cookie("gauth",null,{path:"/",domain:document.domain});else{"."!=c.charAt(0)&&(c="."+c);$.cookie("gauth",null,{path:"/",domain:c});$.cookie("gauth",null,{path:"/",domain:document.domain});var a=b.indexOf(":"),c=b.substr(0,a),b=b.substr(a+1),f=d+"/auth/global/write?authToken="+
encodeURIComponent(c)+"&nonce="+encodeURIComponent(b);$(document).ready(function(){$("#footer").append("<iframe style='display:none' src='"+f+"'></iframe>")})}}},checkStackAuth:function(d){if(gauth.enabled()&&null==$.cookie("gauthed")){$.cookie("gauthed","1",{path:"/"});var c=function(b){if(b.origin==d)if("No Local Storage"==b.data)gauth.noGAuthStorage();else if("No Session"==b.data)gauth.noGAuthSession();else{var a=b.data.substr(0,b.data.indexOf(",")),b=b.data.substr(b.data.indexOf(",")+1);$.post("/users/login/global",
{authToken:a,nonce:b},function(a){gauth.globallyAuthed(a)},"json")}};window.attachEvent?window.attachEvent("onmessage",c):window.addEventListener("message",c,!1);$.post("/users/login/global/request","",function(b){var a=d+"/auth/global/read?request="+encodeURIComponent(b.token)+"&nonce="+encodeURIComponent(b.nonce);$(document).ready(function(){$("#footer").append("<iframe id='global-auth-frame' style='display:none' src='"+a+"'></iframe>")})},"json")}},enabled:function(){$.cookie("enabledCheck","1");
if(null==$.cookie("enabledCheck"))return!1;$.cookie("enabledCheck",null);return"undefined"==typeof localStorage?!1:!0},noGAuthStorage:function(){},noGAuthSession:function(){},globallyAuthed:function(d){if(d&&d.Message){var d=d.Message+" ",c,b=!1,a=""+window.location,f=a.indexOf("returnurl=");if(-1!=f){var e=a.indexOf("&",f);-1==e&&(e=a.length);c=decodeURIComponent(a.substring(f+10,e));c=/^(?:http:\/\/|\/)/.test(c)?c.replace(/[^-a-z0-9+&@#\/%?=~_|!:,.;()]/g,""):null}-1!=a.indexOf("/users/login")&&
(b=!0,c=c||"/");StackExchange.helpers.showFancyOverlay({message:b?d+"<br>You are being redirected...":d+(c?"<a href=\"javascript:window.location='"+c+"'\">Click here</a> to return to your last location.":'<a href="javascript:location.reload(true)">Click here</a> to refresh the page.'),showClose:!b,complete:function(){b&&(window.location=c)}})}}}}(),genuwine=function(){var d,c="",b,a,f=[],e=function(){return $(".genu").hasClass("genu-on")},g=function(){var c=$(".genu"),e=$("#seWrapper");if(0==e.length||
0<b||a){k();var e=$("#seWrapper"),d;0<b?(d=$("#seTabInbox"),r(d)):a?(d=$("#seTabNotices"),l(d)):(d=$("#seTabHot"),m(d));d.addClass("seCurrent")}if(d=c.hasClass("genu-on")){$(".unreadCountTab").remove();$(".itemBoxNew").removeClass("itemBoxNew");e.fadeOut("fast");for(e=0;e<f.length;e++)f[e]();f=[];0<a&&$("#portalLink .unreadCount").text(""+a).addClass("newNotices").show().click(g)}else e.fadeIn("fast"),$(".unreadCount").hide();c.toggleClass("genu-on",!d);-1==b&&$(c).ready(function(){$("#seTabInbox").hide()});
i($("#seTabInbox"),$("#seTabNotices"))},i=function(c,e){StackExchange.options.site.isNoticesTabEnabled&&a&&0==e.find(".unreadCountTab").length&&e.prepend('<span class="unreadCountTab newNotices">'+a+"</span>");0<b&&0==c.find(".unreadCountTab").length&&c.prepend('<span class="unreadCountTab">'+b+"</span>")},k=function(){$("#seWrapper").remove();var a='<div id="seWrapper" style="position:absolute; display:none;"><div class="seIntro"><a href="'+c+'">Stack Exchange</a> is a network of free, community-driven Q&A sites.</div><div class="seNav"><ul class="seNavLinks"><li><a id="seTabHot">Hot Questions</a></li><li><a id="seTabSites">All Sites</a></li><li><a id="seTabInbox">Inbox</a></li>'+
(!StackExchange.options.user.isAnonymous&&StackExchange.options.site.isNoticesTabEnabled?'<li><a id="seTabNotices">Notifications</a></li>':"")+'</ul></div><div class="seContainer"></div><div class="seFooter">'+(!StackExchange.options.user.isAnonymous?'<div id="seTabEmail" class="seEmailAccount"><a>email settings</a></div>':"")+'<a id="seClose">close</a></div></div>',b=$("#hlinks"),b=b.height()+b.offset().top+5;$(a).appendTo("#portalLink").css({top:b}).find("ul.seNavLinks a, #seTabEmail").click(function(){var a=
$(this);$(".seNavLinks a").removeClass("seCurrent");a.addClass("seCurrent");switch(a.attr("id")){case "seTabHot":m(a);$("#seContainerSites, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerHot").fadeIn("fast");break;case "seTabSites":0==$("#seContainerSites").length&&n(a);$("#seContainerHot, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerSites").fadeIn("fast");break;case "seTabInbox":r(a);$("#seContainerHot, #seContainerSites, #seContainerEmail, #seContainerNotices").hide();
$("#seContainerInbox").fadeIn("fast");break;case "seTabEmail":0==$("#seContainerEmail").length&&j(a);$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerNotices").hide();$("#seContainerEmail").fadeIn("fast");break;case "seTabNotices":l(a),$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerEmail").hide(),$("#seContainerNotices").fadeIn("fast")}});$("#seClose").click(function(){g()})},l=function(a){0==$("#seContainerNotices").length&&q(a,"/notices/genuwine?userId="+
StackExchange.options.user.id,"jsonp",h,!0)},h=function(b,c){for(var e='<div id="seContainerNotices" style="display:none">',d=0;d<c.length;d++)var j=c[d],e=e+('<div class="noticeBox'+(j.is_unread?" itemBoxNew":"")+'"><a href="'+j.site_url+'" class="siteLinkFavicon"><img src="'+j.icon+'"></a><div class="siteInfo"><p>'+j.text+"</p></div></div>");u(b,e+"</div>");f.push(function(){a=0;i($("#seTabInbox"),$("#seTabNotices"))});a=0},n=function(a){q(a,c+"/genuwine/sites?callback=?&host="+document.location.host+
(d?"&accountId="+d:""),"jsonp",v)},m=function(a){0==$("#seContainerHot").length&&q(a,c+"/genuwine?callback=?","jsonp",o)},j=function(a){q(a,"/accounts/email-settings","json",function(a,b){function c(){$("#email-save").removeAttr("disabled");$("#email-confirmation").html("")}u(a,'<div id="seContainerEmail" style="display:none; font-size:11px;"><div class="itemBox" style="border-bottom: 0px"><p>Would you like to receive unread inbox messages via email?</p><div>Email: <input id="email-notify" name="email-notify" style="width:300px;" value="'+
b.verifiedEmail+'"></input></div><div><input type="radio" name="optIn" value="true" id="email-enable"'+(!0==b.optIn?'checked="checked"':"")+'"> <label for="email-enable">Email me my unread inbox messages </label> <select id="email-freq"><option value="3">every 3 hours</option><option value="24">daily</option><option value="168">weekly</option></select> </div><div><input type="radio" name="optIn" value="false" id="email-disable"'+(!0!=b.optIn?'checked="checked"':"")+'"> <label for="email-disable">Do not email me inbox messages</label></input></div><div><input type="button" name="save" id="email-save" value="Save" disabled="disabled"></input></div><div id="email-confirmation" style="display:none;"></div></div></div>');
$("#email-freq").val(b.freq).on("click focus",function(){$("#email-enable").prop("checked",!0)});$("#email-notify").focus().keyup(c);$("#email-enable, #email-disable, #email-freq").change(c);$("#email-save").click(function(){w();$.post("/accounts/verified-email-set",{email:$("#email-notify").val(),fkey:StackExchange.options.user.fkey,optin:$("input[name=optIn]:checked").val(),freq:$("#email-freq").val()},function(a){$(".seContainer").removeSpinner();$("#email-confirmation").html(a.message).fadeIn();
a.success&&$("#email-save").attr("disabled","disabled")},"json")})},!0)},o=function(a,b){for(var c=$("<div/>"),e='<div id="seContainerHot" style="display:none">',d=0;d<b.length;d++)var f=b[d],j=f.SiteId,g='href="http://'+j+"/q/"+f.Id+'?hq=1"',k=parseInt(f.DisplayScore,10),e=e+('<div class="itemBox"><a '+g+' class="seNumAnswer">'+k+'</a><div class="siteInfo"><p><a '+g+">"+c.text(f.Title).html()+'</a></p><a href="http://'+j+'" class="siteLink">'+j+"</a></div></div>");u(a,e+"</div>")},n=function(a){q(a,
c+"/genuwine/sites?callback=?&host="+document.location.host+(d?"&accountId="+d:""),"jsonp",v)},v=function(a,b){for(var c='<div id="seContainerSites" style="display:none">',e=0;e<b.length;e++)var d=b[e],f=d.Name,j='href="http://'+d.Id+'?as=1"',c=c+('<div class="itemBox"><a '+j+' class="siteFavicon"><img src="'+d.FaviconUrl+'" alt="'+f+'"></a><div class="siteInfo"><p><a '+j+">"+f+"</a></p><a "+j+' class="siteLink">'+d.Description+"</a></div></div>");u(a,c+"</div>")},r=function(a){-1!=b&&(0==$("#seContainerInbox").length||
0<b)&&t(a)},t=function(a){q(a,"/inbox/genuwine","json",s,!0)},s=function(a,c){for(var e='<div id="seContainerInbox" style="display:none">',j=0;j<c.length;j++){var g=c[j],k='href="'+g.Url+'"',h='title="'+g.CreationDate+'"',r=g.Count,e=e+('<div class="itemBox'+(g.IsNew?" itemBoxNew":"")+'"><a '+k+' class="siteLinkFavicon"><img src="'+g.FaviconUrl+'" alt="'+g.SiteUrl+'"></a><div class="siteInfo">');"careers message"==g.Type?e+="<p><a "+k+' style="font-weight:normal"><b>'+g.Title+"</b> wants to contact you on <b>Stack Overflow Careers</b></a></p>":
"invitation"==g.Type?(h=g.Count,e+="<p><a "+k+' style="font-weight:normal"><b>'+h+"</b> "+("invitation"+(1<h?"s":""))+" awarded on <b>Stack Overflow Careers</b></a></p>"):e+="<p>"+(1<r?r+" ":"")+g.Type+" on <a "+k+" "+h+">"+g.Title+"</a></p>";e+='<p class="inboxSummary">'+(g.Summary||"")+"</p></div></div>"}d&&5<=c.length&&(e+='<div class="itemMoreContainer"><div class="seIntro"><a href="http://stackexchange.com/users/'+d+'?tab=inbox">more inbox messages &hellip;</a></div></div>');u(a,e+"</div>");
f.push(function(){b=0;i($("#seTabInbox"),$("#seTabNotices"))});b=0},p={},q=function(a,b,c,e,d){var f=a.attr("id");if(p[f])w();else{p[f]=!0;w();var j=function(){p[f]=!1;StackExchange.helpers.showErrorPopup($(".seContainer"),"An error occurred while loading - please try again.")};$.ajax({type:"GET",url:b,dataType:c,success:function(b){p[f]=!1;b&&(0<b.length||d)?e(a,b):j()},error:j,complete:function(){$(".seContainer").removeSpinner()}})}},u=function(a,b){var c=$(b);c.prependTo(".seContainer");a.hasClass("seCurrent")&&
c.fadeIn("fast")},w=function(){StackExchange.helpers.removeSpinner();StackExchange.helpers.addSpinner(".seContainer",{position:"relative",left:"10px",top:"10px"})},x=function(){var a=$("#portalLink .unreadCount"),b=a.css("margin-top");a.css({marginTop:-20,opacity:0}).show().animate({marginTop:b,opacity:1},2E3)},y=function(){var a=$(".unreadCount"),b=a.data("events");(!b||!b.click)&&0<a.length&&a.click(g)};return{isVisible:e,click:g,setUnreadCount:function(a){b=a;var c=$("#seTabInbox");0<a?($("#portalLink .unreadCount").text(b),
c.hasClass("seCurrent")&&e()&&t(c),x()):$("#portalLink .unreadCount").text("").hide();$("#portalLink .unreadCount").removeClass("newNotices");y()},animateInbox:x,init:function(f,j,k){var h=$(".genu");1<=h.length&&(h[0].onclick=null);d=f;c=h.attr("href");b=j;a=k;!(0<b)&&StackExchange.options.site.isNoticesTabEnabled&&(99<a&&(a=99),0<a&&$("#portalLink .unreadCount").text(""+a).addClass("newNotices"),y());h.removeAttr("href").click(g);y();$(document).click(function(a){e()&&!$.contains($("#portalLink")[0],
a.target)&&g()})}}}();
StackExchange.notify=function(){function d(a,b){var c=$("#dismissed-messages");c.val(c.val()+"~"+a+(b?" "+b:"")+"~")}function c(a,b){var c=$("#dismissed-messages").val();return!c?!1:RegExp("~"+a+(b?" "+b:"")+"~").test(c)}function b(a,b,c){var e=parseInt($("body").css("margin-top").match(/\d+/)),a=b*e/a;c?$("body:not(.no-message-slide)").animate({marginTop:a+"px"},"fast","linear"):$("body:not(.no-message-slide)").css("marginTop",a+"px")}var a=0,f=function(c,e){var f=$("#notify-"+c+(e?"-"+e:""));-1==
c?$.cookie("m","0",{expires:90,path:"/"}):-1<c&&$.post("/messages/mark-as-read",{messagetypeid:c,id:e?e:null});d(c,e);a--;f.fadeOut("fast",function(){b(a+1,a,!0);f.remove()})},e=function(b){a++;if(c(b.messageTypeId,b.id))return!1;var e="";b.messageTypeId&&(e=' id="notify-'+b.messageTypeId+(b.id?"-"+b.id:"")+'"');e="<div"+e+' style="display:none"><span class="notify-close"><a title="dismiss this notification">&times;</a></span><span class="notify-text">'+b.text+"</span>";if(b.showProfile)var d=encodeURIComponent("/users/"+
b.userId+"?tab=badges&sort=recent"),e=e+(' See your <a href="/messages/mark-as-read?messagetypeid='+b.messageTypeId+"&returnurl="+d+'">profile</a>.');e=$(e+"</div>");e.find(".notify-close").click(function(){b.close&&b.close();f(b.messageTypeId,b.id)});$("#notify-container").append(e);return!0},g=function(){$("#notify-container div").fadeIn("slow")},i=function(a,b){var c=$('<div class="link-more"><a>view '+a+" more notification"+(1!=a?"s":"")+"</a></div>");$("#notify-container").append(c);c.click(function(){c.detach();
for(var a=0;a<b.length;a++)e(b[a]);g()})};return{showMessages:function(c,d){for(var f=0,n=d?2:c.length,m=0;m<n&&m<c.length;m++)e(c[m])&&f++;b(a,f,!1);g();d&&f<c.length&&(n=c.slice(n),i(c.length-f,n))},show:function(a,b){$("body:not(.no-message-slide)").animate({marginTop:"2.5em"},"fast","linear");e({text:a,messageTypeId:b});g()},close:f,getMessageText:function(a){return $("#notify-"+a+" .notify-text").text()}}}();
function moveScroller(){var d=$("#scroller").width(),c=function(){var b=$(window).scrollTop(),a=$("#scroller-anchor").offset().top,c=$("#scroller");b>a?c.height()>$(window).height()?c.css({position:"fixed",top:"",bottom:"0px",width:d}):c.css({position:"fixed",top:"0px",bottom:"",width:d}):b<=a&&c.css({position:"relative",top:"",bottom:""})};$(window).scroll(c).resize(c);c()}
var styleCode=function(){return function(){"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);var d=!1;$("pre code").parent().each(function(){$(this).hasClass("prettyprint-override")&&($(this).removeClass("prettyprint-override").addClass("prettyprint"),d=!0);var c;if(c=!$(this).hasClass("prettyprint")){c=$(this);var b=$("#prettify-lang").text();""!=b?(c.addClass(b),c=!0):c=!1}c&&($(this).addClass("prettyprint"),d=!0)});d&&("undefined"!=typeof jtab?jtab.renderimplicit():StackExchange.using("prettify",
function(){StackExchange.prettify.applyCodeStyling()}))}}();
StackExchange.helpers.MagicPopup=function(d){function c(a,c){var e=$("<div id='"+d.id+"'/>").html(c),g=$("<div />").css({overflow:"hidden",position:"absolute",width:1,height:1,top:0,left:0}).append(e).appendTo("body"),i=d.showing(a,e),j={left:i.left};i.hasOwnProperty("bottom")?(j.bottom=i.bottom,j.top="auto"):j.top=i.top;var o;d.shown&&(o=function(){d.shown(a,e)});g.css(j).animate({height:e.outerHeight()+8,width:e.outerWidth()+8},300,o);b=function(){g.stop().remove();d.removed&&d.removed(a,e);b=f=
null};f=StackExchange.helpers.DelayedReaction(b,5);j=g;i.additional&&(j=j.add(i.additional));j.hover(f.cancel,f.trigger)}var b,a,f,e,g={},i=StackExchange.helpers.DelayedReaction(function(a,f){if(!e&&a){var i;d.cache&&"c_"+a in g?i=$.Deferred().resolve(g["c_"+a]):(i=$.ajax({type:"GET",url:a,dataType:"html"}),d.cache&&i.done(function(b){g["c_"+a]=b}));i.done(function(a){b&&b();""!=a&&c(f,a)})}},500);$(document).delegate(d.selector,{mouseenter:function(){if(f&&this===a)f.cancel();else return a=this,
i.trigger(d.getUrl(this),this),e=!1},mouseleave:function(){e=!0;i.cancel();f&&f.trigger()}})};
StackExchange.tagmenu=function(){function d(a){var a=$(a),b=a.attr("href");if(!b||"/"!=b.charAt(0))return null;b=a.text();if(-1<b.indexOf("*"))return null;a.attr("title","");return"/tags/"+encodeURIComponent(b)+"/subscriber-info"}function c(a,b){var c=$(a),d=c.offset(),k=c.outerHeight(),c={left:d.left},l=d.top+k,k=d.left+b.outerWidth();b.height()+l>$(window).height()+$(window).scrollTop()?c.bottom=$(window).height()-d.top-8:c.top=l;d=Math.max(1024,$(window).width());k>d&&(c.left-=k-d);return c}var b,
a;return{init:function(f){b=f;a||(a=!0,StackExchange.options.isMobile||(StackExchange.helpers.MagicPopup({selector:".post-tag:not(.user-tag)",id:"tag-menu",getUrl:d,showing:c,shown:function(a,c){b&&b(c,$(a).text())}}),$("#interesting-tags .post-tag").addClass("user-tag")))}}}();
StackExchange.usermenu=function(){function d(b,c){var d=$(b).find("img:first"),i=d.offset(),k=d.height(),l=d.width(),h=Math.max(l,k),n=64*k/h,h=64*l/h,m=c.find("img:first").css({width:h,height:n}),j=m.offset();m.css("visibility","hidden");a=d.clone().css({position:"absolute",zIndex:300,left:i.left,top:i.top,width:l,height:k}).appendTo("body");var o=function(){m[0].complete?(m.css("visibility","visible"),a.fadeOutAndRemove()):setTimeout(o,500)};a.animate({width:h,height:n,top:i.top+j.top},200,o);return{top:i.top,
left:i.left-j.left,additional:a}}function c(){a.remove()}var b,a;return{init:function(){b||(b=!0,StackExchange.options.isMobile||StackExchange.helpers.MagicPopup({selector:".user-hover .user-gravatar48, .user-hover .user-gravatar32",getUrl:function(a){a=/\/users\/([^/]+).*$/.exec($(a).closest(".user-hover").find(".user-details a").attr("href"));return!a?null:"/users/user-info/"+a[1]},cache:!0,id:"user-menu",showing:d,removed:c}))}}}();
StackExchange.chatAd=function(){function d(){var a=$(".question .post-taglist .post-tag");return!a.length?null:a.map(function(a,b){return $(b).text()}).get().join(" ")}function c(a){return 10>a?"0"+a:a}function b(a){var b=new Date;b.setTime(1E3*a);return[b.getUTCFullYear(),"-",c(b.getUTCMonth()+1),"-",c(b.getUTCDate())," ",c(b.getUTCHours()),":",c(b.getUTCMinutes()),":",c(b.getUTCSeconds()),"Z"].join("")}function a(a){var b=Math.floor((new Date).getTime()/1E3)-a,e=b%60,d=Math.floor(b/60),f=Math.floor(b/
3600);if(1>b)return"just now";if(60>b)return 1==e?"1 sec ago":e+" secs ago";if(3600>b)return 1==d?"1 min ago":d+" mins ago";if(86400>b)return 1==f?"1 hour ago":f+" hours ago";b=Math.floor(b/86400);if(1==b)return"yesterday";if(2>=b)return b+" days ago";a=new Date(1E3*a);return o[a.getMonth()]+" "+a.getDate()+" at "+a.getHours()+":"+c(a.getMinutes())}function f(a){var b=$("<div />");b.text(a);return b.html().replace('"',"&quot;")}function e(){$.get(h,null,function(a,b,c){k(a,b,c)})}function g(b){for(var c=
$('<div class="ad502-users" />'),e=0;e<b.length&&7>e;e++){var d=b[e],f=d.name;d.lastPost&&(f+=": "+a(d.lastPost));var j="http://www.gravatar.com/avatar/"+d.emailhash+"?s=23&d=identicon&r=PG",d=$('<a href="'+(l+"/users/"+d.id)+'" />');$("<img />").attr("title",f).attr("src",j).appendTo(d);c.append(d)}return c}function i(a){var b=a.user;return(a=a.userid)?'<a href="'+l+"/users/"+a+'">'+f(b)+"</a>":f(b)}function k(c){var d=$("#ad502-rooms");if(!c.error){d.html("");for(var t=c.rooms,h=0;h<t.length&&2>
h;h++){var p=t[h],k=l+"/rooms/"+p.id,o=$('<div class="ad502-room"></div>');o.append($('<h3 class="ad502-room-h3"><span class="ad502-room-title" title="'+f(p.name)+'"><a href="'+k+'">'+f(p.name)+"</a></span></h3>"));p.messages&&0<p.messages.length&&o.append($('<span title="'+b(p.lastPost)+'" class="ad502-last-message">'+a(p.lastPost)+" - "+i(p.messages[0])+"</span><br>"));p.singleImage?o.append($('<div class="ad502-users"><img src="'+l+"/rooms/users/"+p.id+'.jpeg" /></div>')):o.append(g(p.users));
d.append(o)}1<c.activeUsers?$("#h-chat-link").text(c.activeUsers+" People Chatting"):$("#h-chat-link").text("Visit Chat");$("#h-chat-link").attr("title",c.activeUsers+" users active in "+c.activeRooms+" rooms the last 60 minutes")}n<=j&&window.setTimeout(e,1E3*n);n+=m}var l,h,n=180,m=30,j=480,o="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");/^\/questions\/\d+/i.test(window.location.pathname)&&(j=0);return{init:function(a){l=a.chatUrl;h=a.reloadUrl;if(a.tagBased){var b=d();if(!b)return;
h+=(/\?/.test(h)?"&":"?")+"tags="+encodeURIComponent(b)}null===a.preloadData?e():k(a.preloadData,null,null)}}}();
StackExchange.helpers.noDiacritics=function(){var d={"\u00e0\u00e5\u00e1\u00e2\u00e4\u00e3\u00e5\u0105\u0250\u1d44\u1d9b":"a","\u00e6\u01e3\u01fd\u1d02\u1d46":"ae","\u00e7\u0107\u010d\u0109":"c","\u0111\u018d\u00f0\u00d0":"d","\u00e8\u00e9\u00ea\u00eb\u0119\u01dd\u1d08\u1d4c":"e","\u214e":"f","\u011f\u011d\u1d77":"g","\u0125\u0265\u02ae\u1da3":"h","\u00ec\u00ed\u00ee\u00ef\u0131\u1d09\u1d4e":"i","\u0135":"j","\u029e":"k","\u0142":"l","\u026f\u0270\u1d5a\u1dad\u1d1f":"m","\u00f1\u0144":"n","\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u0151":"o",
"\u0153\u0276\u1d14":"oe","\u0159\u0279\u027a\u027b\u02b4\u02b5":"r","\u015b\u015f\u0161\u015d":"s","\u00df":"ss","\u0287":"t","\u00de":"th","\u00f9\u00fa\u00fb\u00fc\u016d\u016f":"u","\u028c\u1dba":"v","\u028d":"w","\u00fd\u0178\u00ff\u028e":"y","\u017c\u017a\u017e":"z"};return function(c){for(var b in d)d.hasOwnProperty(b)&&(c=c.replace(RegExp("["+b+"]"),d[b]));return c}}();
function sanitizeAndSplitTags(d,c){for(var d=$.trim(d).replace(/([A-Za-z0-9])\+(?=[A-Za-z0-9])/g,"$1 "),b=d.split(/[\s|,;]+/),a=[],f=0;f<b.length;f++){var e=StackExchange.helpers.noDiacritics(b[f].toLowerCase()).replace(/_/g,"-"),e=e.replace(RegExp("[^a-z0-9.#+"+(c?"*":"")+"-]","g"),""),e=e.replace(/^[#+-]+/,""),e=e.replace(/[.-]+$/,"");0<e.length&&-1==$.inArray(e,a)&&a.push(e)}return a}
StackExchange.question=function(){var d=function(a,b){var c=null!=a;a||(a=$('div.question div.post-menu a:contains("link")'));var e=a.closest(".post-menu, .help-menu");if(a.hasClass("share-link"))e.find(".close-share-tip").click();else{a.addClass("share-link");var d=a.attr("id").substring(10),f=a.closest(".col-section").length?"section":a.closest("div.question").length?"question":"answer",g=$('<div class="share-tip" style="display:none">share a link to this '+f+'<input type="text" value="http://'+
document.location.host+a.attr("href")+'" style="display:block; width:292px;"><a class="close-share-tip" style="float:right">close</a></div>');b&&g.find(".close-share-tip").before('<a id="link-post-'+d+'" style="float:left">cite</a>');g.appendTo(e).fadeIn(c?"fast":0).bind("removing",function(){a.removeClass("share-link")}).find(".close-share-tip").click(function(){g.fadeOutAndRemove()}).end().find("input[type=text]").select()}},c=function(a){var b=$("#post-form h2:first"),c=b.wrap("<div />").parent(),
e=c.wrap("<div />").parent(),d=$("<div />").prependTo(e),f=e.height(),g=$("<div />"),a=$(a),i=parseInt(b.css("margin-bottom")),h=$("#content"),k=$("#wmd-input").outerWidth(),l=h.offset().left>b.offset().left-5&&"visible"!=h.css("overflow-x");g.css({height:0,overflowY:"hidden"}).appendTo(c).append(a);e.css({height:f,position:"relative"});c.css({position:"absolute",bottom:-i,width:k});d.addClass("answer-help-background").css({position:"absolute",bottom:-i,height:0,width:k});l&&(d.css("left",0),c.animate({paddingLeft:5},
1E3));g.animate({height:a.height()+i+10},1E3);d.animate({height:a.height()+i+10+f},1E3);$("<div style='float:right;margin-top:10px;'><a href='#'>ok</a></div>").hide().prependTo(c).fadeIn(1E3).find("a").one("click",function(a){var e=$(this).parent();setTimeout(function(){e.remove()},1);g.animate({height:0},1E3,function(){g.add(d).remove();b.unwrap().unwrap()});d.animate({height:0},1E3);l&&c.animate({paddingLeft:0},1E3);a.preventDefault()})},b=function(){$.get("/posts/answer-help").then(c)},a,f,e,g=
function(){var a=window.location.href;0>a.indexOf("#")||(a=a.match(/#(\d+|comment(\d+)_(\d+))/i))&&(a[2]?i(a[2],a[3]):k($(".answer[data-answerid="+a[1]+"]")))},i=function(a,b){var c="#comment-"+a,e=$(c);e.length?k(e):StackExchange.comments.loadAll($("#comments-link-"+b)).done(function(){k($(c))})},k=function(b){var c=e;b.css({backgroundColor:a}).animate({backgroundColor:c},2E3,"linear",function(){$(this).css("background-color","")});b.is(".comment")&&b[0].scrollIntoView(!0)},l=function(a){a=a||{};
$('.post-menu a:contains("link")').live("click",function(b){if(!b.ctrlKey&&!b.metaKey)return d($(this),a.showCitation),!1})},h=null,n=function(a,b,c){if(!h&&!a.is(":focus"))return!0;var e=b.find(".title-float-option"),d=h?e.index(h):-1,d=d+c;if(-1>d||d>=e.length)return!0;b.find(".title-float-selected").removeClass("title-float-selected");if(-1==d)return h=null,a.focus(),!1;h=e.eq(d);h.addClass("title-float-selected");return!1},m=function(a,b){if(a.is(":focus")){var c=a.offset(),e=$(b);e.find(".answer-summary").addClass("title-float-option");
e.find(".answer-link a").attr("target","_blank");var d=$(".title-search-float");0==d.length?(a.focus(function(){0<d.children().length&&setTimeout(function(){d.show()},0)}),d=$('<div class="title-search-float"></div>'),a.parent().append(d),$(document).keydown(function(b){if(27==b.keyCode||9==b.keyCode)d.hide(),$(".title-float-selected").removeClass("title-float-selected"),h=null;if(38==b.keyCode)return n(a,d,-1);if(40==b.keyCode)return n(a,d,1);if(13==b.keyCode&&(b=d.find(".title-float-selected:visible"),
0!=b.length))return b=b.find("a").attr("href"),window.open(b,"_blank"),!1}),$(document).click(function(b){var c=$(b.target)[0]==a[0];0==$(b.target).parents(".title-search-float").length&&!c&&d.hide()}),$(window).resize(function(){if(d.is(":visible")){var b=a.offset(),c=b.top+a.outerHeight();d.width(a.outerWidth()-2+"px");d.offset({top:c,left:b.left})}})):d.show();d.empty();var f=c.top+a.outerHeight();d.append(e);d.css({position:"absolute"});d.width(a.outerWidth()-2+"px");d.offset({top:f,left:c.left})}};
return{initTitleSearch:function(a,b,c){var e=0,d;a.attr("autocomplete","off");var f=function(){var f=a.val();if(!(f==d||StackExchange.options.site.newTitleSearchBoxEnabled&&0<$(".title-float-selected:visible").length)){for(var g=f.split(" "),i=0,h=0;h<g.length;h++)0<$.trim(g[h]).length&&i++;g=(new Date).getTime();h=(g-e)/1E3;3>i||5>h&&!a.hasClass("edit-field-overlayed")||(e=g,d=f,c&&(document.title=f+" - "+c),StackExchange.options.site.newTitleSearchBoxEnabled?(b.addClass("title-loading"),$.ajax({url:"/search/titles?like="+
escape(f),success:function(b){/\<label\>/i.exec(b)||(e=0);m(a,b)},complete:function(){b.removeClass("title-loading")}})):(StackExchange.helpers.addSpinner(b),b.load("/search/titles?like="+escape(f),null,function(a){/\<label\>/i.exec(a)||(e=0);setTimeout(function(){b.find(".answer-link a").attr("target","_blank")},1)})))}},g=function(){e=0;f()};a.keyup(f).blur(g);setInterval(f,100);return g},showShareTip:d,getQuestionId:function(a){a=(a?a.closest(".question"):$(".question")).data("questionid");if(!a)throw Error("getQuestionId could not find an id");
return a},highlightComment:i,initShareLinks:l,canViewVoteCounts:function(){return f},init:function(c){StackExchange.question.fullInit?StackExchange.question.fullInit(c):StackExchange.question.bindAnonymousVoteDisclaimers();StackExchange.comments.init({autoShowCommentHelp:c.autoShowCommentHelp});c.showShareTip&&d();$("input.anon-vote").live("click",function(){var a=$(this),b=a.postId(),c=a.parent();c.closest(".question,.answer").unbind("mouseenter.helpful").unbind("mouseleave.helpful");c.text("sending feedback ...");
setTimeout(function(){c.text("Thank you for your feedback.")},500);$.ajax({type:"POST",url:"/vote/anon/"+b,data:{votetypeid:"Yes"==a.val()?2:3},complete:function(){}})});var i=$(".was-this-helpful"),h=i.css("color"),k=$(".post-text").css("color");i.each(function(){var a=$(this),b=a.text();a.closest(".answer, .question").bind("mouseenter.helpful",function(){a.html("Was this post useful to you? &nbsp;&nbsp;<input style='display:none;' class='anon-vote' type='button' value='Yes'/> &nbsp;<input style='display:none;' class='anon-vote' type='button' value='No'/>").animate({color:k},
"fast","linear").find("input").fadeIn("fast")}).bind("mouseleave.helpful",function(){a.text(b).animate({color:h},"fast","linear")})});l(c);if(c.showAnswerHelp)$("#wmd-input").one("focus",b);c.showCitation&&$("div.share-tip a[id^='link-post-']").live("click",function(){$(this).closest(".post-menu").find(".close-share-tip").click();citation.show($(this))});e=c.backgroundColor;a=c.highlightColor;f=c.canViewVoteCounts;g(c)}}}();
StackExchange.question.bindAnonymousVoteDisclaimers=function(){function d(c){return function(b){var a='Please <a href="/users/login?returnurl='+escape(document.location)+'">login or register</a> to '+c+" this post.";StackExchange.helpers.showErrorPopup($(this).parent(),a);var a="",d=$(this).prop("className"),e=$(this).closest(".answer").length?"answer":"question";/vote-up/.test(d)?a="?vote=up&type="+e:/vote-down/.test(d)?a="?vote=down&type="+e:/star/.test(d)&&(a="?vote=favorite");StackExchange.helpers.fireAndForget("/analytics/user/try-vote"+
a);b.preventDefault()}}$(".vote-up-off, .vote-down-off").click(d("vote for"));$("div.post-menu a[id^='flag-post-']").unbind("click").click(d("flag"));$(".star-off:not(.disabled)").live("click",d("favorite"))};
StackExchange.comments=function(){function d(a,b){this.postId=a;this.jDiv=b;this.jCommentsLink=$("#comments-link-"+a)}function c(b){var c=(b.constructor===$?b:$(b)).closest(".question, .answer, div[id^='post-']").find(".comments"),b=c.attr("id").replace(/^comments-/,"");if(a[b])return a[b];c=new d(b,c);return a[b]=c}function b(){if(0!=$(".question[data-questionid]").length){var a=StackExchange.question.getQuestionId();$(".comment .comment-date > span").each(function(){var b=$(this),c=b.closest(".answer"),
c=c&&c.length?c.data("answerid"):0,d=b.closest(".comment").attr("id").substr(8);b.wrap('<a class="comment-link" onclick="StackExchange.question.highlightComment({cid}, {aid})" href="{hash}"></a>'.format({hash:"#comment"+d+"_"+(c?c:a),cid:d,aid:c}))})}}var a={},f=function(){};d.prototype={checkDiscussion:f,ensureInput:f,commentsShown:function(){this.jCommentsLink.hide();this.jCommentsLink.data("comments-count",0)},addShow:function(a){var b=this;this.loadAllComments().done(function(){b.jCommentsLink.hide();
b.checkDiscussion()});var c=this.ensureInput();c&&!a&&c.focus()},ajax:function(a,b,c,d){c&&!d&&StackExchange.helpers.addSpinner(c,{"margin-left":"10px"});var f=this;return $.ajax(a).fail(function(a){$(".error-notification").fadeOut("fast",function(){$(this).remove()});a=a.responseText;if(!a||100<=a.length)a="An error occured"+(b?" "+b:"");StackExchange.helpers.showErrorPopup(c||f.jDiv,a);c&&!d&&StackExchange.helpers.removeSpinner()}).done(StackExchange.helpers.removeSpinner).promise()},showComments:function(a){this.jDiv.find(" > table > tbody").html(a);
this.jCommentsLink.text("add comment");"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);b();this.commentsShown()},loadAllComments:function(a){this.jDiv.removeClass("dno");if(!a&&!/more comment/.test($("#comments-link-"+this.postId).text()))return $.Deferred().resolve().promise();var b=this;return this.ajax({type:"GET",url:"/posts/"+this.postId+"/comments",dataType:"html"},"while fetching comments").done(function(a){b.showComments(a)}).promise()}};return{init:function(a){a=a&&
a.post||document;$("a[id^='comments-link-']",a).click(function(){var a=/more comment/.test($(this).text());c(this).addShow(a)});a==document&&b()},loadAll:function(a){return c(a).loadAllComments(!0)},extendPostUi:function(a){for(var b in a)a.hasOwnProperty(b)&&(d.prototype[b]=a[b])},uiForPost:c}}();
StackExchange.share=function(){function d(b,a,c){window.open(b,a,c)||(window.location.href=b)}function c(b,a){var c=b.indexOf("?"),d=b.indexOf("#");return-1==c?-1==d?b+"?"+a:b.substring(0,d)+"?"+a+b.substring(d):-1==d?b+"&"+a:b.substring(0,d)+"&"+a+b.substring(d)}return{gplus:function(b,a){a=c(a,"sgp=1");b.click(function(){d("https://plus.google.com/share?url="+a,"sharegplus","toolbar=1,status=1,resizable=1,scrollbars=1,width=600,height=500")})},twitter:function(b,a,f){a=c(a,"stw=1");b.click(function(){d("http://twitter.com/share?url="+
a+"&ref=twitbtn&text="+f,"sharetwitter","toolbar=1,status=1,resizable=1,scrollbars=1,width=800,height=526")})},facebook:function(b,a,f){a=c(a,"sfb=1");b.click(function(){d("http://www.facebook.com/sharer.php?u="+a+"&ref=fbshare&t="+f,"sharefacebook","toolbar=1,status=1,resizable=1,scrollbars=1,width=626,height=436")})}}}();
function initTagRenderer(d,c){window.tagRenderer||(window.tagRendererRaw=function(b,a){var a=a||"",f="";a||(d&&-1<$.inArray(b,d)?f=" required-tag":c&&-1<$.inArray(b,c)&&(f=" moderator-tag"));return"<a class='post-tag"+f+"' href='"+a+"/questions/tagged/"+encodeURIComponent(b)+"' title=\"show questions tagged '"+b+"'\" rel='tag'>"+b+"</a>"},window.tagRenderer=function(b,a){return $(tagRendererRaw(b,a))})}
function showFadingHelpText(d){d.wrap('<div class="dno" />').show().parent().fadeIn("slow",function(){$(this).children().unwrap()})}
function initFadingHelpText(){var d={"wmd-input":"#how-to-format",tagnames:"#how-to-tag","tag-editor":"#how-to-tag",title:"#how-to-title","wmd-input-42":"#how-to-format"},c=$("#wmd-input, #tagnames, #title, .tag-editor input, #wmd-input-42"),b=function(a){return $(a).parent().hasClass("tag-editor")?d["tag-editor"]:d[$(a).attr("id")]};c.focus(function(){var a=b(this);c.each(function(){var c=b(this);c!=a&&$(c).hide()});var d=$(a);d.is(":visible")||showFadingHelpText(d)})}
$.fn.extend({postId:function(){var d=this.first();if(!d.hasClass("answer")||!d.hasClass("question"))d=d.closest(".answer, .question");return parseInt(d.find(".vote input")[0].value)}});
StackExchange.newsletterAd=function(){function d(b){b=$('<div id="lightbox-panel" class="popup newsletter-popup" style="display:block"></div>').append('<div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div>').append(b);$('<div id="lightbox"></div>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");b.appendTo($("body")).center().fadeIn("fast").find(".popup-close").click(function(){$("#lightbox, #lightbox-panel").fadeOutAndRemove()})}function c(){var b=
StackExchange.options.site.name,a=$(['<div style="text-align: left;">','<h2 style="margin-bottom: 15px;">Subscribe to the '+b+" weekly newsletter</h2>",'<p><strong><a href="/users/login?returnurl=/newsletter/signup/redirect">Create an account on '+b+'</a> or <a href="/users/login?returnurl=/newsletter/signup/redirect">log in</a> if you already have one.</strong></p>','<form><label for="newsletter-email-input">Or, send newsletter emails to:</label> <input type="text" id="newsletter-email-input" maxlength="100" title="your email address" /> <input type="submit" value="Subscribe" id="newsletter-email-submit" /></form>',
$("#newsletter-ad .privacy-policy-agreement").parent().html(),"</div>"].join(""));a.find("form").submit(function(){var b=$(this),c=$.trim(a.find("#newsletter-email-input").val());if(0==c.length)return!1;StackExchange.helpers.addSpinner(b);$.ajax({url:"/newsletter/signup/anon",type:"POST",dataType:"json",data:{email:c},success:function(a){"confirmed"==a.status&&!a.error?(b.find("#newsletter-email-input").attr("disabled",!0),b.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),
$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>')):"unconfirmed"==a.status&&!a.error?(b.find("#newsletter-email-input").attr("disabled",!0),b.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),b.append("<br /><br/><p><em>Please click the link in the confirmation email to activate your subscription.</em></p>"),$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>')):
b.showErrorPopup(a.error||"there was a problem signing up for the newsletter<br />please try again later")},error:function(){b.showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner(b)}});return!1});d(a)}return{init:function(){$("#newsletter-signup").click(function(){var b=$(this);if(StackExchange.options.user.isAnonymous)return c(),!1;StackExchange.helpers.addSpinner("#newsletter-signup-container");
$.ajax({url:"/newsletter/signup",type:"POST",dataType:"json",success:function(a){a.url?window.location.href=a.url:"confirmed"==a.status?$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>'):"unconfirmed"==a.status?$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>'):b.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},
error:function(){b.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner("#newsletter-signup-container")}})});$("#newsletter-preview").click(function(){var b=$(window).height(),b=Math.min(600,b-100),b=['<div id="newsleter-preview-pane" style="overflow: hidden; width: 660px; height: ',b,'px;"><iframe src="',$(this).attr("href"),'" width="660" height="',b,'" frameborder="0"></iframe></div>'].join("");
d(b);return!1})},loader:function(b,a){var b=a||b,c=$(".newuser-greeting");$.ajax({url:"/newsletter/targetted/ajax",data:{domain:b},success:function(a){$("#newsletter-ad").remove();c.empty().append($(a))},complete:function(){c.attr("class","").attr("style","")}});a||(window.sessionStorage.tNewsletter=b+"-continued")}}}();
(function(d,c,b,a){d.fn.caret=function(f,e){var g,i,k=this[0],l=d.browser.msie;"object"===typeof f&&"number"===typeof f.start&&"number"===typeof f.end?(g=f.start,i=f.end):"number"===typeof f&&"number"===typeof e?(g=f,i=e):"string"===typeof f?-1<(g=k.value.indexOf(f))?i=g+f[c]:g=null:"[object RegExp]"===Object.prototype.toString.call(f)&&(f=f.exec(k.value),null!=f&&(g=f.index,i=g+f[0][c]));if("undefined"!=typeof g)return l?(l=this[0].createTextRange(),l.collapse(!0),l.moveStart("character",g),l.moveEnd("character",
i-g),l.select()):(this[0].selectionStart=g,this[0].selectionEnd=i),this[0].focus(),this;if(l)if(i=document.selection,"textarea"!=this[0].tagName.toLowerCase()){l=this.val();g=i[b]()[a]();g.moveEnd("character",l[c]);var h=""==g.text?l[c]:l.lastIndexOf(g.text);g=i[b]()[a]();g.moveStart("character",-l[c]);var n=g.text[c]}else g=i[b](),i=g[a](),i.moveToElementText(this[0]),i.setEndPoint("EndToEnd",g),h=i.text[c]-g.text[c],n=h+g.text[c];else h=k.selectionStart,n=k.selectionEnd;g=k.value.substring(h,n);
return{start:h,end:n,text:g,replace:function(a){return k.value.substring(0,h)+a+k.value.substring(n,k.value[c])}}}})(jQuery,"length","createRange","duplicate");
