'use strict';window.StackExchange={};function CTIsPlayback(){try{return parent&&parent.WebPlayer}catch(e){return!1}}if(!CTIsPlayback()&&top!=self)throw top.location.replace(document.location),$(function(){$("head").add("body").remove()}),alert("For security reasons, framing is not allowed; click OK to remove the frames."),Error();
StackExchange.init=function(){var e=function(a){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){e(a)},1E3);else{var d=document.createElement("div");d.id="noscript-padding";var c=document.createElement("div");c.id="noscript-warning";c.innerHTML=a+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(c)}},a=function(){$(document).keyup(function(a){27==a.which&&
($("#lightbox:not(.no-esc-remove), .error-notification, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide())})},f=function(){var a=$("#hlinks"),d=$("#search input[name=q]"),c=d.width(),f=2.5*c,e,h=function(a){d.queue("expand",a)},k=!1,n=!("placeholder"in document.createElement("input"));n&&!StackExchange.options.isMobile&&(""==d[0].value&&(d[0].value="search"),d.bind({focus:function(){"search"==
this.value&&(this.value="")}}));d.keydown(function(c){if(k||46>c.keyCode&&8!=c.keyCode&&32!=c.keyCode)return!0;k=!0;clearTimeout(e);d.clearQueue("expand");h(function(c){d[0].placeholder="";a.fadeOut(100,c)});h(function(c){d.animate({width:f,"max-width":f},100,c)});h(function(){0==d.parent().find(".search-prompt").length&&d.before('<span class="search-prompt">search:</span>')});3==d.queue("expand").length&&d.dequeue("expand")}).focusout(function(){e=setTimeout(function(){h(function(c){d.parent().find(".search-prompt").remove();
c()});h(function(a){d.animate({width:c,"max-width":c},100,a)});h(function(c){n&&""==d[0].value&&(d[0].value="search");d[0].placeholder="search";a.fadeIn(100,c)});3==d.queue("expand").length&&d.dequeue("expand");k=!1},200)});$("#search").keydown(function(c){if(13==c.which&&c.ctrlKey&&d.val())return window.open("/search?q="+encodeURIComponent(d.val()),"_newtab"),!1})};return function(g){StackExchange.options=g;var d=g.serverTime-(new Date).getTime()/1E3;e(g.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();
$(function(){a();f();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0,g.fullPostfix);var c=StackExchange.options.styleCodeAdditionalLang;c&&StackExchange.ifUsing("prettify",function(){return StackExchange.loadJsFile("third-party/prettify/additional-langs/"+c)});StackExchange.ready(function(){genuwine.init(g.user.accountId||null,g.user.inboxUnviewedCount,g.user.notificationsUnviewedCount);g.user.messages&&StackExchange.notify.showMessages(g.user.messages,
g.isMobile);g.site.globalAuthDisabled||(!g.site.isChildMeta&&g.user.isAnonymous&&gauth.checkStackAuth(g.stackAuthUrl),gauth.informStackAuth(g.stackAuthUrl));g.user.isAnonymous||profileLink.init(g.user.gravatar,g.isMobile,g.user.profileUrl+"?tab=activity",d);g.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():StackExchange.tagmenu.init();$("*[data-tracker]").track()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(e){$(function(){var a=$("#debug-messages");a.length||(a=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(e).appendTo(a)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(e){StackExchange.initialized.done(e)};if(window.serq)for(var i=0;i<window.serq.length;i++)StackExchange.ready(window.serq[i]);
(function(){var e={anonymous:"full-anon.js",loggedIn:"full.js",prettify:"prettify-full.js",pseudoModerator:"moderator.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",mathjaxEditingNew:"mathjax-editing-new.js",revisions:"revisions.js",suggestedEdits:"suggested-edits.js",mockups:"mockups.js"},
a={},f={},g,d={},c=function(c,a){return function(d){var f=c[d];f||(f=c[d]=a(d));return f}},l=function(c){var c=a[c],d,f=$.Deferred(),e=$.when(f),g;if(c)for(d=0;d<c.length;d++)(g=c[d].call(null))&&$.isFunction(g.promise)&&(e=$.when(e,g));f.resolve();return e},j=function(){if(!g){var c=$("script[src*='/stub.js']:first");0==c.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),g="/content/js/"):g=c.attr("src").replace(/\/stub\.js.*$/,"/")}return g},h=function(c){var a=$.Deferred(),
d=document.createElement("script");d.async="async";d.type="text/javascript";d.src=c;d.onload=d.onreadystatechange=function(c,f){if(!d.readyState||/loaded|complete/.test(d.readyState))f?a.reject():a.resolve()};d.onerror=function(){a.reject()};$("head")[0].appendChild(d);return a.promise()},k=function(c){c=e[c];return!c?$.Deferred().reject().promise():n(c)},n=c({},function(c){var a=j()+c;var f=d["js/"+c];f?c="?v="+f:(StackExchange.debug.log("no cache breaker for "+c),c="");return h(a+c)}),o=c({},function(c){function a(){(f=
StackExchange[c])?l(c).done(function(){d.resolve()}):0<e?(e--,StackExchange.debug.log("retrying "+c),setTimeout(a,20)):(StackExchange.debug.log("object "+c+" not available although file was loaded"),d.reject())}var d=$.Deferred(),f=StackExchange[c],e=3;f?d.resolve():k(c).done(a).fail(d.reject);return d.promise()}),p=$.Deferred(),q=function(c,a,d,f){if(!d&&!p.isResolved())p.done(function(){q(c,a)});else{if(d)for(var g in e)e.hasOwnProperty(g)&&(e[g]=e[g].replace(/^(full(?:-anon)?).js$/,"$1"+(f||"")+
".js"));f=o(c);d?p.resolve():f=$.when(f,StackExchange.initialized);f.done(function(){a()}).fail(function(){StackExchange.debug.log("failed to provide object "+c)});return f}};q.setCacheBreakers=function(c){for(var a in c)c.hasOwnProperty(a)&&(d[a]=c[a])};StackExchange.using=q;StackExchange.ifUsing=function(c,d,e){if("undefined"!==typeof e){if(f["u_"+e])return;f["u_"+e]=!0}StackExchange[c]?d():((e=a[c])||(e=a[c]=[]),e.push(d))};StackExchange.loadJsFile=function(c){return h(j()+c)}})();
String.prototype.format=function(){var e=this.toString();if(!arguments.length)return e;var a="string"==typeof arguments[0]?arguments:arguments[0],f;for(f in a)e=e.replace(RegExp("\\{"+f+"\\}","gi"),a[f]);return e};String.prototype.truncate=function(e,a){var f=this.toString();e&&f.length>e&&(f=f.substr(0,e)+a);return f};String.prototype.splitOnLast=function(e){e=this.lastIndexOf(e);return 0>e?[this]:[this.substr(0,e),this.substr(e)]};String.prototype.contains=function(e){return-1<this.indexOf(e)};
StackExchange.init.createJqueryExtensions=function(){var e=StackExchange.helpers;$.extend($.expr[":"],{working:function(a){a=$(a).data("working");return"undefined"!==typeof a&&a},data:function(a,f,e){f=e[3];return"undefined"!==typeof $(a).data(f)}});$.fn.extend({working:function(a){return this.each(function(){$(this).data("working",a)})},track:function(){return this.each(function(){var a=$(this),f=a.is("a[href]")?a:a.find("a[href]"),e=a.data("tracker");f.each(function(){var a=this.href.splitOnLast("#"),
c=a[0];this.href=c+=(c.contains("?")?"&":"?")+e+(a[1]||"")})})},fadeOutAndRemove:function(){return this.each(function(){var a=$(this);a.fadeOut("fast",function(){a.trigger("removing").remove()})})},charCounter:function(a){return this.each(function(){var f=a.target?$(a.target):$(this).parents("form").find("span.text-counter"),g=this;$(this).bind("blur focus keyup paste",e.DelayedReaction(function(){var d=a.min,c=a.max,e=a.setIsValid||function(){},j=g.value?g.value.replace(/\r\n/g,"\n").length:0,h=
j>0.8*c?"supernova":j>0.6*c?"hot":j>0.4*c?"warm":"cool",k="";0==j?(k="enter at least "+d+" characters",e(!1)):j<d?(k=d-j+" more to go...",e(!1)):(k=c-j+" character"+(1!=c-j?"s":"")+" left",e(j<=c));f.text(k);f.hasClass(h)||f.removeClass("supernova hot warm cool").addClass(h)},100,{sliding:!0}).trigger)})},selectRange:function(a,f){return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(a,f);else if(this.createTextRange){var e=this.createTextRange();e.collapse(!0);
e.moveEnd("character",f);e.moveStart("character",a);e.select()}})},addSpinner:function(a){return this.each(function(){e.addSpinner(this,a)})},addSpinnerAfter:function(a){return this.each(function(){$(this).after(e.getSpinnerImg(a))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorPopup:function(a,f,g){return this.each(function(){e.showErrorPopup(this,a,f,g)})},center:function(){var a=this.parent();"static"===a.css("position")&&(a=a.offsetParent());
var a=a.offset(),e=$(window);this.css("position","absolute");this.css("top",(e.height()-this.height())/2+e.scrollTop()-a.top+"px");this.css("left",(e.width()-this.width())/2+e.scrollLeft()-a.left+"px");return this},helpOverlay:function(){e.bindHelpOverlayEvents(this);return this},hideHelpOverlay:function(){e.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer").removeClass("disabled-button"):this.attr("disabled",
"disabled").css("cursor","default").addClass("disabled-button");return this},disable:function(){return this.enable(!1)},loadPopup:function(a){var f=this;f.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:a.url,dataType:"html",success:function(e){var d=$(e);d.find(".popup-actions-cancel, .popup-close a").click(function(){d.fadeOutAndRemove();a.lightbox&&$("#lightbox").fadeOutAndRemove()});d.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");a.hideDescriptions&&
d.find("ul.action-list > li:not(.action-selected) .action-desc").hide();e=d.find("input:radio:not(.action-subform input)");e.closest("li").bind("hide-action",function(){var c=$(this),d=".action-subform"+(a.hideDescriptions?", .action-desc":"");c.removeClass("action-selected").find(d).slideUp("fast")}).bind("show-action",function(){var c=$(this);c.hasClass("action-selected")||(c.siblings(".action-selected").trigger("hide-action"),c.addClass("action-selected").find(".action-subform").slideDown("fast",
function(){a.subformShow&&a.subformShow($(this));if(a.subformFocusInput){var c=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);c.length&&c.focus()}}),a.hideDescriptions&&c.find(".action-desc").slideDown("fast"),a.actionSelected&&a.actionSelected(c),d.find(".popup-submit").enable())});e.click(function(){$(this).closest("li").trigger("show-action")});d.appendTo(f.parent());a.loaded&&a.loaded(d);e=function(){};if(a.subformShow){var c=d.find("li.action-selected .action-subform");
0<c.length&&(e=function(){c.each(function(){a.subformShow($(this))})})}if(a.lightbox){var l=$('<div id="lightbox"/>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");d.css("z-index",l.css("z-index")+1)}a.dontCenter||d.center().fadeIn("fast",e)},error:function(){f.parent().showErrorPopup("Unable to load popup - please try again")},complete:e.removeSpinner});return f}})};
StackExchange.helpers=function(){function e(c,a,d){for(var e=0;e<d.length;e++){var f=d[e];try{if(/\*/.test(f))for(var n=0;4>n;n++){var o=f.replace(/\*/g,g[n]),p=c.css(o);a.css(o,p)}else a.css(f,c.css(f))}catch(q){}}}function a(c,a,d,f){if(c.is(":visible")){var g=$.browser.msie?0:0.4;d()?(c.css("opacity",g+(f?0.2:0)),c.addClass("edit-field-overlayed"),d=c.prev(".actual-edit-overlay"),0==d.length&&(f=c.parent().find("span.edit-field-overlay").text(),d=c.width(),g=c.height(),d=c.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:d,height:g}),d.is("textarea,input")?(d.val(f),e(a,d,["line-height"])):d.text(f).css("line-height",g+"px").prepend("&nbsp;"),e(a,d,["font-family","font-size","text-align"]),e(c,d,["border-*-style","border-*-color","border-*-width"]),c.css({zIndex:1,position:"relative"}),d.insertBefore(c),f=c.offset().top-
d.offset().top,0!=f&&(a=parseInt(d.css("margin-top")),f=a+f,c.is("textarea")||(f=parseInt(d.prevAll(":visible").eq(0).css("margin-bottom"))+a),d.css("margin-top",f)),c=c.offset().left-d.offset().left,0!=c&&(a=parseInt(d.css("margin-left")),d.css("margin-left",a+c)))):c.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function f(c,a){$(c).find("input[type='submit']").prop("disabled",a)}var g=["left","right","top","bottom"],d={genericBindOverlayEvents:function(c,e,f){StackExchange.options.isMobile||
e.bind("keydown contextmenu",function(){d.hideHelpOverlay(c)}).focus(function(){a(c,e,f,!0)}).blur(function(){a(c,e,f)}).each(function(){a(c,e,f)})},bindHelpOverlayEvents:function(c){c.each(function(){var c=$(this);d.genericBindOverlayEvents(c,c,function(){return""===c.val()})})},hideHelpOverlay:function(c){c.css("opacity",1);c.css("filter","");c.removeClass("edit-field-overlayed")},onClickDraftSave:function(c){$(c).click(function(){var c=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=
null;window.location.href=c});return!1});return!0},showErrorPopup:function(c,a,d,e){$(".error-notification").remove();var f=$('<div class="error-notification supernovabg"><h2>'+a+"</h2>"+(d?"":'<span class="error-close">(click on this box to dismiss)</span>')+"</div>"),g=function(){f.fadeOutAndRemove();e&&e()};$(c).append(f);f.click(g).fadeIn("fast");setTimeout(g,d?Math.max(2500,40*a.length):3E4)},removeErrorPopup:function(){$(".error-notification").fadeOutAndRemove()},addSpinner:function(c,a){$(c).append(d.getSpinnerImg(a))},
getSpinnerImg:function(c){var a=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');c&&a.css(c);return a},removeSpinner:function(){$("img.ajax-loader").remove()},enableSubmitButton:function(c){f(c,!1)},disableSubmitButton:function(c){f(c,!0)},loadTicks:function(c){var a;a=c?c.find(".edit-block"):$(".edit-block");0==a.find("input[name=i1l]").length&&!a.data("loading-ticks")&&(a.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(c){a.append("<input type='hidden' name='i1l' value='"+
c+"' />")},complete:function(){a.data("loading-ticks",!1)}}))},showFancyOverlay:function(c){var c=c||{},a=$("#overlay-header"),d=c.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==c.showClose&&(d+='<br><a class="close-overlay">close this message</a>');a.html(d).css(e).animate({opacity:"1",height:"show"},"slow",c.complete).find(".close-overlay").click(function(){a.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(c,a,d){var d=d||{},e,f,g=d.always,o=function(){e=
null;c.apply(null,f)};return{trigger:function(){f=arguments;g&&g.apply(null,f);e?d.sliding&&(clearTimeout(e),e=setTimeout(o,a)):e=setTimeout(o,a)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(c){$.ajax({type:"POST",url:c,async:!0})}};return d}();
function prepareEditor(e){var a=e.postfix||"",f=function(){setTimeout(function(){StackExchange.editor.initIfShown(e)},1)};if(e.onDemand){for(var g="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),d=$('<ul id="wmd-button-row'+a+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),c=0,l=0;l<g.length;l++){var j=g[l],h=/spacer/.test(j),j=$("<li id='wmd-"+j+a+
"' />").prop("className","wmd-"+(h?"spacer":"button")).css("left",25*l).appendTo(d);$("<span />").css("background-position",c+"px -20px").appendTo(j);h||(c-=20)}var k=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){k||(k=!0,d.addSpinner({"float":"right"}),StackExchange.using("editor",function(){d.remove();e.autoShowMarkdownHelp&&(e.immediatelyShowMarkdownHelp=!0);f()}))})}else StackExchange.using("editor",f)}
StackExchange.switchMobile=function(e,a){$.post("/mobile/"+e,{returnurl:a},function(a){window.location=a})};
jQuery.cookie=function(e,a,f){if("undefined"!=typeof a){f=f||{};null===a&&(a="",f.expires=-1);var g="";if(f.expires&&("number"==typeof f.expires||f.expires.toUTCString))"number"==typeof f.expires?(g=new Date,g.setTime(g.getTime()+864E5*f.expires)):g=f.expires,g="; expires="+g.toUTCString();var d=f.path?"; path="+f.path:"",c=f.domain?"; domain="+f.domain:"",f=f.secure?"; secure":"";document.cookie=[e,"=",encodeURIComponent(a),g,d,c,f].join("")}else{a=null;if(document.cookie&&""!=document.cookie){f=
document.cookie.split(";");for(g=0;g<f.length;g++)if(d=jQuery.trim(f[g]),d.substring(0,e.length+1)==e+"="){a=decodeURIComponent(d.substring(e.length+1));break}}return a}};jQuery.expr[":"].regex=function(e,a,f){var a=f[3].split(","),g=/^(data|css):/,f=a[0].match(g)?a[0].split(":")[0]:"attr",g=a.shift().replace(g,"");return RegExp(a.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(e)[f](g))};
$.extend($.expr[":"],{containsExact:function(e,a,f){return $.trim(e.innerHTML.toLowerCase())===f[3].toLowerCase()},containsExactCase:function(e,a,f){return $.trim(e.innerHTML)===f[3]},containsRegex:function(e,a,f){a=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(f[3]);return RegExp(a[1],a[2]).test($.trim(e.innerHTML))}});
$.extend({URLEncode:function(e){for(var a="",f=0,e=e.toString(),g=/(^[a-zA-Z0-9_.]*)/;f<e.length;){var d=g.exec(e.substr(f));null!=d&&1<d.length&&""!=d[1]?(a+=d[1],f+=d[1].length):(" "==e[f]?a+="+":(d=e.charCodeAt(f).toString(16),a+="%"+(2>d.length?"0":"")+d.toUpperCase()),f++)}return a},URLDecode:function(e){for(var a,f=/(%[^%]{2})/;null!=(m=f.exec(e))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),a=String.fromCharCode(b),e=e.replace(m[1],a);return e}});
(function(e){e.fn.typeWatch=function(a){function f(a){if("TEXT"==a.type.toUpperCase()||"TEXTAREA"==a.nodeName.toUpperCase()){var c={timer:null,text:e(a).val().toUpperCase(),cb:g.callback,el:a,wait:g.wait};g.highlight&&e(a).focus(function(){this.select()});var f=function(a){var d=c.wait,f=!1;13==a.keyCode&&"TEXT"==this.type.toUpperCase()&&(d=1,f=!0);clearTimeout(c.timer);c.timer=setTimeout(function(){var a=f,d=e(c.el).val();if(d.length>g.captureLength&&d.toUpperCase()!=c.text||a&&d.length>g.captureLength)c.text=
d.toUpperCase(),c.cb(d)},d)};e(a).keydown(f).bind("paste",null,function(c){c.which||f(this)})}}var g=e.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},a);return this.each(function(){f(this)})}})(jQuery);
(function(e){function a(a){var d;return a&&a.constructor==Array&&3==a.length?a:(d=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])]:(d=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(d[1]),2.55*parseFloat(d[2]),2.55*parseFloat(d[3])]:(d=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(d[1],16),parseInt(d[2],16),parseInt(d[3],16)]:
(d=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(d[1]+d[1],16),parseInt(d[2]+d[2],16),parseInt(d[3]+d[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?f.transparent:f[e.trim(a).toLowerCase()]}e.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(f,d){e.fx.step[d]=function(c){if(!c.colorInit){var f;f=c.elem;var g=d,h;do{h=e.curCSS(f,g);if(""!=h&&"transparent"!=h||e.nodeName(f,"body"))break;g="backgroundColor"}while(f=f.parentNode);
f=a(h);c.start=f;c.end=a(c.end);c.colorInit=!0}c.elem.style[d]="rgb("+[Math.max(Math.min(parseInt(c.pos*(c.end[0]-c.start[0])+c.start[0]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[1]-c.start[1])+c.start[1]),255),0),Math.max(Math.min(parseInt(c.pos*(c.end[2]-c.start[2])+c.start[2]),255),0)].join()+")"}});var f={transparent:[255,255,255]}})(jQuery);
